'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=__dirname,version=require('./package.json').version;
const output=path.join(root,'offline','WPS-SKU-Cleaner_'+version);
fs.mkdirSync(output,{recursive:true});
const bundle='// Generated by build.cjs. Edit js/SkuCleaner.js and addin/adapter.js, then rebuild.\n'+
  fs.readFileSync(path.join(root,'js/SkuCleaner.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'addin/adapter.js'),'utf8');
fs.writeFileSync(path.join(root,'addin/main.js'),bundle);
fs.writeFileSync(path.join(output,'main.js'),bundle);
fs.writeFileSync(path.join(output,'index.html'),'<!doctype html><html><head><meta charset="utf-8"><script src="./main.js"></script></head><body></body></html>\n');
fs.copyFileSync(path.join(root,'addin/ribbon.xml'),path.join(output,'ribbon.xml'));
console.log('Offline WPS bundle generated: '+output);
