// Generated by build.cjs. Edit js/SkuCleaner.js and addin/adapter.js, then rebuild.
/* WPS desktop JSA macro. Import this whole file into one module.
 * No Node.js, network, filesystem or additional libraries required in WPS.
 */
var SKU_CONFIG = { headerRow: 0, scanRows: 20, headerContains: true,
    maxColumns: 256, sliceCells: 25, sliceMs: 24, pauseMs: 8, batchRows: 1000,
    maxCells: 200000, fallbackRows: 20000, maxSheets: 100, maxAreas: 32 };
var SKU_STATE = typeof SKU_STATE === "object" ? SKU_STATE : {
    enabled: false, busy: false, registered: false, workbook: null, last: null
};

function skuCleanText(value) {
    return String(value).replace(/[\s\u00A0\u200B-\u200F\u202A-\u202E\u2060\uFEFF]/g, "")
        .replace(/^[\u0027\u2018\u2019]+/, "")
        .replace(/[\uFF10-\uFF19]/g, function (c) { return String(c.charCodeAt(0) - 65296); });
}
function skuClassify(value) {
    if (value === null || value === undefined || value === "") return { kind: "blank" };
    if (typeof value === "number") {
        if (!isFinite(value) || value < 0 || Math.floor(value) !== value) return { kind: "invalid" };
        if (value > 999999999999999) return { kind: "long" };
        return { kind: "numeric", value: value };
    }
    if (typeof value !== "string") return { kind: "invalid" };
    var cleaned = skuCleanText(value);
    if (!cleaned) return { kind: "blankText" };
    if (!/^[0-9]+$/.test(cleaned)) return { kind: "text", value: cleaned };
    var significant = cleaned.replace(/^0+/, "") || "0";
    if (significant.length > 15) return { kind: "long" };
    return { kind: "convert", value: Number(significant) };
}
function skuIsHeader(value) {
    if (typeof value !== "string") return false;
    var text = skuCleanText(value).toLowerCase();
    return SKU_CONFIG.headerContains ? text.indexOf("sku") !== -1 : text === "sku";
}
function skuStats() {
    return { columns: 0, converted: 0, numeric: 0, textFormatted: 0, blank: 0, invalid: 0,
        long: 0, formula: 0, merged: 0, protectedSheets: 0, failed: 0,
        visited: 0, writes: 0, batches: 0, fallbackCells: 0, elapsedMs: 0, limited: 0, samples: [] };
}
function skuSample(stats, sh, row, col, reason) {
    if (stats.samples.length < 10) stats.samples.push(sh.Name + "!R" + row + "C" + col + ": " + reason);
}
function skuBounds(target) {
    if (!target) return null;
    var result = [], areas = target.Areas;
    if (areas.Count > SKU_CONFIG.maxAreas) throw new Error("选区过于零散，请分次处理（最多32个区域）。");
    for (var i = 1; i <= areas.Count; i++) {
        var a = areas.Item(i);
        result.push({ top: a.Row, bottom: a.Row + a.Rows.Count - 1,
            left: a.Column, right: a.Column + a.Columns.Count - 1 });
    }
    return result;
}
function skuProcessCell(sh, row, col, stats) {
    stats.visited++;
    var cell = sh.Cells.Item(row, col);
    if (cell.MergeCells) { stats.merged++; return; }
    if (cell.HasFormula) { stats.formula++; return; }
    var value = cell.Value2;
    // Do not format truly empty cells, including formatted tails in UsedRange.
    if (value === null || value === undefined || value === "") { stats.blank++; return; }
    if (Application.WorksheetFunction.IsError(cell)) { stats.invalid++; return; }
    var outcome = skuClassify(value), format = String(cell.NumberFormat);
    if (outcome.kind === "long" || outcome.kind === "invalid") {
        stats[outcome.kind]++;
        skuSample(stats, sh, row, col, outcome.kind === "long" ? "超过15位，原样保留" : "不支持的数值/类型，原样保留");
        return;
    }
    if (outcome.kind === "text") {
        if (value !== outcome.value) {
            // Only changed strings are written. Text format prevents coercion.
            var staged = false, written = false;
            try {
                if (format !== "@") { cell.NumberFormat = "@"; stats.writes++; staged = true; }
                cell.Value2 = outcome.value; stats.writes++; written = true;
            } finally {
                if (written) { cell.NumberFormat = "0"; stats.writes++; }
                else if (staged) { cell.NumberFormat = format; stats.writes++; }
            }
        } else if (format !== "0") { cell.NumberFormat = "0"; stats.writes++; }
        stats.textFormatted++;
    } else {
        if (format !== "0") { cell.NumberFormat = "0"; stats.writes++; }
        if (outcome.kind === "convert") { cell.Value2 = outcome.value; stats.writes++; stats.converted++; }
        else if (outcome.kind === "numeric") stats.numeric++;
        else { cell.ClearContents(); stats.writes++; stats.blank++; }
    }
}
function skuColumnName(col) {
    var result = "";
    while (col > 0) { col--; result = String.fromCharCode(65 + col % 26) + result; col = Math.floor(col / 26); }
    return result;
}
function skuColumnRange(sh, row, col, count) {
    var name = skuColumnName(col);
    return sh.Range(name + row + ":" + name + (row + count - 1));
}
function skuVector(raw, count) {
    if (count === 1 && !Array.isArray(raw)) return [raw];
    if (!Array.isArray(raw) || raw.length !== count) throw new Error("批量数据不是预期的数组。");
    return raw.map(function (item) {
        if (Array.isArray(item)) {
            if (item.length !== 1) throw new Error("批量数据列数不匹配。");
            return item[0];
        }
        return item;
    });
}
function skuMask(special, row, col, count) {
    var mask = [], areas = special.Areas;
    if (areas.Count > 64) throw new Error("特殊单元格过于零散。");
    for (var i = 0; i < count; i++) mask.push(false);
    for (var a = 1; a <= areas.Count; a++) {
        var area = areas.Item(a), top = area.Row, end = top + area.Rows.Count;
        // Reject unexpected expanded/out-of-scope SpecialCells results.
        if (area.Column !== col || area.Columns.Count !== 1 || top < row || end > row + count) {
            throw new Error("特殊单元格范围越界。");
        }
        for (var r = top; r < end; r++) mask[r - row] = true;
    }
    return mask;
}
function skuBulkPlan(sh, row, col, count) {
    // Read and validate the complete plan before writing. Never include formulas,
    // errors, booleans, merged cells or precision-sensitive identifiers in a write.
    var range = skuColumnRange(sh, row, col, count);
    if (range.MergeCells !== false) return null;
    var hasFormula = range.HasFormula;
    if (hasFormula === true) return { range: range, formulaOnly: true, count: count };
    var values = skuVector(range.Value2, count), eligible, formulas = [];
    if (values.every(function (v) { return v === null || v === undefined || v === ""; }) && hasFormula === false) {
        return { range: range, blankOnly: true, count: count };
    }
    eligible = skuMask(range.SpecialCells(2, 3), row, col, count); // constants: numbers + text
    if (hasFormula !== false) formulas = skuMask(range.SpecialCells(-4123), row, col, count);
    var groups = [], group = null, outcomes = [];
    for (var i = 0; i < count; i++) {
        var out = formulas[i] ? { kind: "formula" } : !eligible[i] ?
            { kind: values[i] === null || values[i] === undefined || values[i] === "" ? "blank" : "invalid" } : skuClassify(values[i]);
        outcomes.push(out);
        if (out.kind === "convert" || out.kind === "numeric" || out.kind === "text" || out.kind === "blankText") {
            if (!group) { group = { offset: i, values: [], changed: false, text: false }; groups.push(group); }
            var next = out.kind === "blankText" ? null : out.value;
            group.values.push([next]);
            if (values[i] !== next) group.changed = true;
            if (typeof next === "string") group.text = true;
        } else group = null;
    }
    if (groups.length > 64) return null;
    return { range: range, outcomes: outcomes, groups: groups, count: count };
}
function skuBulkWrite(sh, row, col, plan, stats) {
    stats.visited += plan.count; stats.batches++;
    if (plan.formulaOnly) { stats.formula += plan.count; return; }
    if (plan.blankOnly) { stats.blank += plan.count; return; }
    for (var i = 0; i < plan.groups.length; i++) {
        var g = plan.groups[i];
        var range = g.offset === 0 && g.values.length === plan.count ? plan.range :
            skuColumnRange(sh, row + g.offset, col, g.values.length);
        var format = range.NumberFormat, written = false, staged = false;
        if (g.changed) {
            try {
                // Typed numbers stay numeric even under @. Text, including =1+2,
                // stays literal. This is verified in the in-WPS bulk self-test.
                var writeFormat = g.text ? "@" : "0";
                if (String(format) !== writeFormat) { range.NumberFormat = writeFormat; stats.writes++; staged = true; }
                range.Value2 = g.values.length === 1 ? g.values[0][0] : g.values;
                stats.writes++; written = true;
            } finally {
                if (written && g.text) { range.NumberFormat = "0"; stats.writes++; }
                else if (!written && staged) {
                    // Mixed old formats cannot be restored with a scalar format.
                    range.NumberFormat = typeof format === "string" ? format : "0"; stats.writes++;
                }
            }
        } else if (String(format) !== "0") { range.NumberFormat = "0"; stats.writes++; }
    }
    plan.outcomes.forEach(function (out, index) {
        var key = out.kind === "convert" ? "converted" : out.kind === "text" ? "textFormatted" :
            out.kind === "blankText" ? "blank" : out.kind;
        stats[key]++;
        if (key === "long") skuSample(stats, sh, row + index, col, "超过15位，原样保留");
    });
}
function skuProcessBlock(sh, span, stats) {
    var count = Math.min(span.batchRows || SKU_CONFIG.batchRows, span.bottom - span.row + 1);
    var plan = null, start = Date.now();
    if (count > 1) {
        try { plan = skuBulkPlan(sh, span.row, span.col, count); }
        catch (ignored) { plan = null; } // Probe only; write failures never silently retry.
    }
    if (!plan && count > 25) {
        span.batchRows = Math.floor(count / 2); return;
    }
    if (plan) {
        try { skuBulkWrite(sh, span.row, span.col, plan, stats); }
        catch (err) {
            stats.failed++; skuSample(stats, sh, span.row, span.col, "批量写入失败: " + String(err.message || err));
            throw new Error("批量写入失败，已停止。已完成的修改保留: " + String(err.message || err));
        }
        span.row += count;
        if (Date.now() - start > 80) span.batchRows = Math.max(64, Math.floor(count / 2));
    } else {
        var processed = 0;
        do {
            try { skuProcessCell(sh, span.row, span.col, stats); }
            catch (err) {
                stats.failed++; skuSample(stats, sh, span.row, span.col, "写入失败: " + String(err.message || err));
                if (stats.failed >= 10) throw new Error("累计10个写入错误，已停止并暂停自动处理。");
            }
            stats.fallbackCells++; span.row++; processed++;
        } while (processed < Math.min(count, 25) && span.row <= span.bottom && Date.now() - start < SKU_CONFIG.sliceMs);
        // Retry bulk processing after passing a small exceptional/merged region.
        span.batchRows = SKU_CONFIG.batchRows;
    }
}
function skuLastDataRow(sh, col, top, bottom) {
    if (top > bottom) return top - 1;
    try {
        var name = skuColumnName(col), range = sh.Range(name + top + ":" + name + bottom);
        // Specify all Find options; do not inherit the user's Find dialog options.
        var found = range.Find("*", undefined, -4123, 2, 1, 2, false, false, false);
        return found ? found.Row : top - 1;
    } catch (err) {
        // Unsupported host API must never lead to a million-row fallback scan.
        if (bottom - top + 1 > SKU_CONFIG.fallbackRows) throw new Error("无法确定SKU数据末行，请选择不超过20000行的区域后处理。");
        return bottom;
    }
}
function skuIntervals(bounds, col, top, bottom) {
    var ranges = [];
    if (!bounds) ranges.push([top, bottom]);
    else for (var i = 0; i < bounds.length; i++) {
        var b = bounds[i];
        if (col >= b.left && col <= b.right) ranges.push([Math.max(top, b.top), Math.min(bottom, b.bottom)]);
    }
    ranges.sort(function (a, b) { return a[0] - b[0]; });
    var merged = [];
    ranges.forEach(function (a) {
        if (a[0] > a[1]) return;
        var prev = merged[merged.length - 1];
        if (prev && a[0] <= prev[1] + 1) prev[1] = Math.max(prev[1], a[1]);
        else merged.push(a.slice());
    });
    return merged;
}
function skuTask(book, sheets, bounds, notify, limit) {
    return { book: book, sheets: sheets, bounds: bounds, notify: notify, stats: skuStats(),
        index: 0, state: null, done: false, planned: 0, started: null, limit: limit || SKU_CONFIG.maxCells };
}
function skuPrepareSheet(task) {
    if (task.index >= task.sheets.length) { task.done = true; return; }
    var sh = task.sheets[task.index++];
    if (sh.ProtectContents) { task.stats.protectedSheets++; return; }
    var used = sh.UsedRange, firstCol = used.Column;
    var lastCol = Math.min(used.Column + used.Columns.Count - 1, SKU_CONFIG.maxColumns);
    var lastRow = used.Row + used.Rows.Count - 1;
    if (used.Column + used.Columns.Count - 1 > SKU_CONFIG.maxColumns) {
        task.stats.limited++; skuSample(task.stats, sh, 1, 257, "仅检查前256列");
    }
    task.state = { sh: sh, r: SKU_CONFIG.headerRow || used.Row,
        end: SKU_CONFIG.headerRow || Math.min(lastRow, SKU_CONFIG.scanRows),
        c: firstCol, firstCol: firstCol, lastCol: lastCol, lastRow: lastRow,
        columns: [], phase: "header", planCol: 0, spans: [], spanIndex: 0 };
}
function skuStepUnit(task) {
    if (!task.state) { skuPrepareSheet(task); return; }
    var s = task.state, stats = task.stats;
    if (s.phase === "header") {
        if (s.r > s.end || s.firstCol > s.lastCol) { task.state = null; return; }
        var cell = s.sh.Cells.Item(s.r, s.c);
        if (!cell.HasFormula && !cell.MergeCells && skuIsHeader(cell.Value2)) s.columns.push(s.c);
        s.c++;
        if (s.c > s.lastCol) {
            if (s.columns.length) { s.header = s.r; s.phase = "plan"; }
            else { s.r++; s.c = s.firstCol; }
        }
        return;
    }
    if (s.phase === "plan") {
        if (s.planCol >= s.columns.length) { s.phase = "data"; return; }
        var col = s.columns[s.planCol++];
        var ranges = skuIntervals(task.bounds, col, s.header + 1, s.lastRow);
        // Limit Find to the requested rows. Header-only edits do not trigger a full scan.
        if (!ranges.length) return;
        var bottom = skuLastDataRow(s.sh, col, ranges[0][0], ranges[ranges.length - 1][1]);
        ranges = skuIntervals(task.bounds, col, s.header + 1, bottom);
        if (ranges.length) stats.columns++;
        for (var i = 0; i < ranges.length; i++) {
            task.planned += ranges[i][1] - ranges[i][0] + 1;
            s.spans.push({ col: col, row: ranges[i][0], bottom: ranges[i][1] });
        }
        if (task.planned > task.limit) throw new Error("本次范围超过" + task.limit + "个SKU单元格，请选择较小区域分次处理。已完成的修改保留。");
        return;
    }
    var span = s.spans[s.spanIndex];
    if (!span) { task.state = null; return; }
    skuProcessBlock(s.sh, span, stats);
    if (span.row > span.bottom) s.spanIndex++;
}
function skuHostSlice(task) {
    if (task.started === null) task.started = Date.now();
    var app = Application, oldEvents, oldScreen, eventsRead = false, screenRead = false;
    SKU_STATE.busy = true;
    try {
        oldEvents = app.EnableEvents; eventsRead = true; app.EnableEvents = false;
        oldScreen = app.ScreenUpdating; screenRead = true; app.ScreenUpdating = false;
        // Protection can change between slices; never continue writing a protected sheet.
        if (task.state && task.state.sh.ProtectContents) {
            task.stats.protectedSheets++; task.state = null;
        }
        if (task.state && task.state.phase === "data") {
            var current = task.state.spans[task.state.spanIndex];
            if (current) {
                var header = task.state.sh.Cells.Item(task.state.header, current.col);
                if (header.HasFormula || header.MergeCells || !skuIsHeader(header.Value2)) {
                    throw new Error("处理期间SKU表头发生变化，已停止；请重新选择范围处理。");
                }
            }
        }
        var start = Date.now(), units = 0;
        while (!task.done && units < SKU_CONFIG.sliceCells && Date.now() - start < SKU_CONFIG.sliceMs) {
            var before = task.stats.visited;
            skuStepUnit(task); units++;
            // Yield after one block rather than holding the host for 25 bulk writes.
            if (task.stats.visited > before) break;
        }
    } finally {
        try { if (screenRead) app.ScreenUpdating = oldScreen; }
        finally { try { if (eventsRead) app.EnableEvents = oldEvents; } finally {
            SKU_STATE.busy = false; task.stats.elapsedMs = Date.now() - task.started;
        } }
    }
}
// Small isolated self-tests only. Production buttons/events always use the scheduler.
function skuExecute(book, sheet, target) {
    if (SKU_STATE.busy) return null;
    var sheets = sheet ? [sheet] : skuSheets(book);
    var task = skuTask(book, sheets, skuBounds(target), false, 2000);
    while (!task.done) skuHostSlice(task);
    SKU_STATE.last = task.stats;
    return task.stats;
}
function skuSheets(book) {
    if (book.Worksheets.Count > SKU_CONFIG.maxSheets) throw new Error("工作表超过100张，请处理当前表或所选区域。");
    var sheets = [];
    for (var i = 1; i <= book.Worksheets.Count; i++) sheets.push(book.Worksheets.Item(i));
    return sheets;
}
function skuReport(stats) {
    return "匹配列: " + stats.columns + "\n检查单元格: " + stats.visited + "\n写入接口调用: " + stats.writes +
        "\n批量处理块: " + stats.batches + "\n兼容处理单元格: " + stats.fallbackCells +
        "\n用时（秒）: " + (stats.elapsedMs / 1000).toFixed(2) +
        "\n文本转数字: " + stats.converted + "\n数字格式检查: " + stats.numeric +
        "\n非数字文本整理: " + stats.textFormatted + "\n空白跳过/清理: " + stats.blank +
        "\n跳过错误/不支持类型: " + stats.invalid + "\n保留超长编号: " + stats.long +
        "\n跳过公式: " + stats.formula + "\n跳过合并单元格: " + stats.merged +
        "\n跳过受保护表: " + stats.protectedSheets + "\n写入失败: " + stats.failed + "\n范围限制: " + stats.limited +
        (stats.samples.length ? "\n\n示例位置（最多10条）:\n" + stats.samples.join("\n") : "");
}
var SKU_RUN = { current: null, pending: [], timer: null, enabled: false, book: null, error: "", slices: 0 };
function skuSameBook(a, b) {
    if (!a || !b) return false;
    try { return a === b || String(a.FullName).toLowerCase() === String(b.FullName).toLowerCase(); }
    catch (ignored) { return false; }
}
function skuSchedule() {
    if (typeof setTimeout !== "function") throw new Error("当前宿主不支持分批调度，请使用离线加载项。自动处理已暂停。");
    if (SKU_RUN.timer !== null) return;
    SKU_RUN.timer = setTimeout(skuTick, SKU_CONFIG.pauseMs);
}
function skuStop(silent) {
    if (SKU_RUN.timer !== null && typeof clearTimeout === "function") clearTimeout(SKU_RUN.timer);
    SKU_RUN.timer = null; SKU_RUN.enabled = false;
    if (SKU_RUN.current) SKU_STATE.last = SKU_RUN.current.stats;
    SKU_RUN.current = null; SKU_RUN.pending = [];
    if (!silent) alert("已停止排队和后续处理，并暂停自动处理。已完成的修改保留；尚未自动保存。");
}
function skuTick() {
    SKU_RUN.timer = null;
    try {
        if (!SKU_RUN.current) SKU_RUN.current = SKU_RUN.pending.shift() || null;
        var task = SKU_RUN.current;
        if (!task) return;
        skuHostSlice(task); SKU_RUN.slices++;
        SKU_STATE.last = task.stats;
        if (task.done) {
            SKU_RUN.current = null;
            if (task.benchmark) {
                var testSheet = task.sheets[0];
                // Four sample reads avoid host differences in one-row array shape.
                var passed = testSheet.Cells.Item(2, 1).Value2 === 123 && testSheet.Cells.Item(20001, 1).Value2 === 123 &&
                    testSheet.Cells.Item(2, 2).Value2 === "ABC-123" && testSheet.Cells.Item(20001, 2).Value2 === "ABC-123" &&
                    testSheet.Range("A2:B20001").HasFormula === false && String(testSheet.Range("A2:B20001").NumberFormat) === "0" &&
                    task.stats.converted === 20000 && task.stats.textFormatted === 20000 && task.stats.failed === 0 && task.stats.fallbackCells === 0;
                alert((passed ? "2万行两列测速通过。" : "2万行测速未全部通过，请查看处理模式和错误。") +
                    "\n仅使用新建的未保存测试文件，已有文件未用于测速。\n" + skuReport(task.stats));
            } else if (task.notify) alert("SKU处理完成\n" + skuReport(task.stats));
        }
        if (SKU_RUN.current || SKU_RUN.pending.length) skuSchedule();
    } catch (err) {
        SKU_RUN.error = String(err.message || err);
        skuStop(true);
        alert("SKU处理已停止，自动处理已暂停。\n" + SKU_RUN.error);
    }
}
function skuQueue(book, sheets, bounds, notify) {
    if (typeof setTimeout !== "function") throw new Error("当前宿主不支持分批调度，请使用离线加载项。");
    if (notify && (SKU_RUN.current || SKU_RUN.pending.length)) throw new Error("已有任务正在处理，请等待完成或点击停止处理。");
    // Coalesce only queued changes. Never replace an in-progress task's row cursor.
    if (!notify) for (var i = 0; i < SKU_RUN.pending.length; i++) {
        var p = SKU_RUN.pending[i];
        if (!p.notify && skuSameBook(p.book, book) && p.sheets[0].Name === sheets[0].Name) {
            var combined = skuMergeBounds(p.bounds.concat(bounds));
            if (combined.length > SKU_CONFIG.maxAreas) throw new Error("变化过于频繁，已暂停；请手动处理所选区域。");
            p.bounds = combined; return;
        }
    }
    if (SKU_RUN.pending.length >= 32) throw new Error("排队任务过多，已暂停；请稍后手动处理。");
    SKU_RUN.pending.push(skuTask(book, sheets, bounds, notify));
    SKU_RUN.error = "";
    try { skuSchedule(); }
    catch (err) { SKU_RUN.error = String(err.message || err); skuStop(true); throw err; }
}
function skuMergeBounds(bounds) {
    var result = [];
    bounds.forEach(function (b) {
        var item = { top: b.top, bottom: b.bottom, left: b.left, right: b.right };
        for (var i = result.length - 1; i >= 0; i--) {
            var a = result[i];
            if ((a.left === item.left && a.right === item.right && a.top <= item.bottom + 1 && item.top <= a.bottom + 1) ||
                (a.top === item.top && a.bottom === item.bottom && a.left <= item.right + 1 && item.left <= a.right + 1)) {
                item.top = Math.min(a.top, item.top); item.bottom = Math.max(a.bottom, item.bottom);
                item.left = Math.min(a.left, item.left); item.right = Math.max(a.right, item.right);
                result.splice(i, 1); i = result.length;
            }
        }
        result.push(item);
    });
    return result;
}
function skuManual(selected, wholeBook) {
    try {
        var book = Application.ActiveWorkbook;
        if (!book) throw new Error("请先打开工作簿。");
        var sheets = wholeBook ? skuSheets(book) : [Application.ActiveSheet];
        var bounds = selected ? skuBounds(Application.Selection) : null;
        if (selected && (!bounds || !bounds.length)) throw new Error("请先选择需要处理的单元格区域。");
        skuQueue(book, sheets, bounds, true);
    } catch (err) { alert("无法开始SKU处理: " + String(err.message || err)); }
}
function SKU_CleanCurrentSheet() { skuManual(false, false); }
function SKU_CleanWorkbook() { skuManual(false, true); }
function SKU_CleanSelection() { skuManual(true, false); }
function skuOnChange(sh, target) {
    if (!SKU_RUN.enabled || SKU_STATE.busy || !sh || !target) return;
    try {
        if (!skuSameBook(sh.Parent, SKU_RUN.book)) return;
        var bounds = skuBounds(target);
        // SheetChange only snapshots the target; no cell reads/writes or full scans here.
        skuQueue(sh.Parent, [sh], bounds, false);
    } catch (err) { SKU_RUN.error = String(err.message || err); skuStop(true); alert("SKU自动处理已暂停: " + SKU_RUN.error); }
}
function skuOnClose(book) {
    if (skuSameBook(book, SKU_RUN.book) || (SKU_RUN.current && skuSameBook(book, SKU_RUN.current.book)) ||
        SKU_RUN.pending.some(function (task) { return skuSameBook(book, task.book); })) {
        skuStop(true); SKU_RUN.book = null;
    }
}
function skuRegister() {
    if (SKU_STATE.registered) return;
    if (!SKU_STATE.changeRegistered) {
        Application.ApiEvent.AddApiEventListener("SheetChange", skuOnChange);
        SKU_STATE.changeRegistered = true;
    }
    try { Application.ApiEvent.AddApiEventListener("WorkbookBeforeClose", skuOnClose); }
    catch (err) { throw new Error("无法监听文件关闭，未启用自动处理: " + String(err.message || err)); }
    SKU_STATE.registered = true;
}
function SKU_EnableAuto() {
    try {
        if (!Application.ActiveWorkbook) throw new Error("请先打开工作簿。");
        if (typeof setTimeout !== "function") throw new Error("宿主不支持分批调度，请使用离线加载项。");
        skuRegister(); SKU_RUN.book = Application.ActiveWorkbook; SKU_RUN.enabled = true;
        alert("已开启当前文件的输入/粘贴自动处理。已有数据请点击处理当前表。\n打开其他文件、切换表不会扫描；重启WPS后需重新开启。");
    } catch (err) { SKU_RUN.enabled = false; alert("无法启用自动处理: " + String(err.message || err)); }
}
function SKU_DisableAuto() { skuStop(false); }
function SKU_Status() {
    alert("自动处理: " + (SKU_RUN.enabled ? "开启（当前绑定文件）" : "暂停") +
        (SKU_RUN.book ? "\n绑定文件: " + SKU_RUN.book.Name : "") +
        "\n任务: " + (SKU_RUN.current || SKU_RUN.pending.length ? "分批处理中" : "空闲") +
        "\n待处理任务: " + SKU_RUN.pending.length +
        (SKU_STATE.last ? "\n\n最近一次/当前进度:\n" + skuReport(SKU_STATE.last) : "") +
        (SKU_RUN.error ? "\n\n错误: " + SKU_RUN.error : ""));
}

// Loading never scans or edits workbooks. Auto mode is session-only and opt-in.
var SKU_ADDIN = { loaded: false, registered: false, errors: [] };
function skuAddinError(err) {
    if (SKU_ADDIN.errors.length < 10) SKU_ADDIN.errors.push(String(err.message || err));
}
function SkuAddinLoad(ribbonUI) {
    try {
        if (!window.Application && typeof wps !== "undefined" && wps.EtApplication) window.Application = wps.EtApplication();
        if (!window.Application) throw new Error("WPS没有提供Application接口。");
        SKU_ADDIN.loaded = true;
        skuRegister(); SKU_ADDIN.registered = true;
    } catch (err) { skuAddinError(err); }
    return true;
}
function SkuAddinEnableAuto() { SKU_EnableAuto(); }
function SkuAddinDisableAuto() { SKU_DisableAuto(); }
function SkuAddinStop() { skuStop(false); }
function SkuAddinStatus() {
    alert("SKU工具 v1.0.5\n宿主代码加载: " + (SKU_ADDIN.loaded ? "成功" : "失败") +
        "\n事件注册: " + (SKU_ADDIN.registered ? "成功" : "失败") +
        "\n自动处理: " + (SKU_RUN.enabled ? "开启（仅绑定文件）" : "暂停") +
        (SKU_RUN.book ? "\n绑定文件: " + SKU_RUN.book.Name : "") +
        "\n任务: " + (SKU_RUN.current || SKU_RUN.pending.length ? "分批处理中" : "空闲") +
        "\n待处理任务: " + SKU_RUN.pending.length +
        (SKU_STATE.last ? "\n\n最近一次/当前进度:\n" + skuReport(SKU_STATE.last) : "\n尚未处理数据。") +
        (SKU_RUN.error ? "\n\n处理错误:\n" + SKU_RUN.error : "") +
        (SKU_ADDIN.errors.length ? "\n\n加载错误:\n" + SKU_ADDIN.errors.join("\n") : ""));
}
function SkuAddinSelfTest() {
    if (SKU_RUN.current || SKU_RUN.pending.length) { alert("请先等待当前任务完成或点击停止处理，再运行自测。"); return; }
    var app = Application, oldEvents = app.EnableEvents, oldAuto = SKU_RUN.enabled;
    var passed = false, message = "";
    try {
        SKU_RUN.enabled = false;
        app.EnableEvents = false;
        var book = app.Workbooks.Add(), sh = book.Worksheets.Item(1);
        sh.Name = "SKU工具自测";
        sh.Range("A1:C8").NumberFormat = "@";
        sh.Cells.Item(1, 1).Value2 = "公司sku";
        sh.Cells.Item(1, 2).Value2 = "平台sku";
        sh.Cells.Item(1, 3).Value2 = "其他列";
        sh.Cells.Item(2, 1).Value2 = "'2714230032211";
        sh.Cells.Item(3, 1).Value2 = "２７１４２３００３２２１１";
        sh.Cells.Item(4, 1).Value2 = " 'AB C-１２３";
        sh.Cells.Item(5, 1).Value2 = "1000000000000001";
        sh.Cells.Item(6, 1).NumberFormat = "General";
        sh.Cells.Item(6, 1).Formula = "=1+2";
        sh.Cells.Item(7, 1).Value2 = " =1+2 ";
        sh.Cells.Item(8, 1).Value2 = "1E12";
        sh.Cells.Item(2, 2).Value2 = "000123";
        sh.Cells.Item(2, 3).Value2 = "000123";
        var stats = skuExecute(book, sh, null);
        passed = typeof sh.Cells.Item(2, 1).Value2 === "number" && sh.Cells.Item(2, 1).Value2 === 2714230032211 &&
            String(sh.Cells.Item(2, 1).NumberFormat) === "0" && sh.Cells.Item(3, 1).Value2 === 2714230032211 &&
            sh.Cells.Item(2, 2).Value2 === 123 && sh.Cells.Item(4, 1).Value2 === "ABC-123" && String(sh.Cells.Item(4, 1).NumberFormat) === "0" &&
            sh.Cells.Item(5, 1).Value2 === "1000000000000001" && sh.Cells.Item(6, 1).HasFormula &&
            sh.Cells.Item(7, 1).Value2 === "=1+2" && !sh.Cells.Item(7, 1).HasFormula && sh.Cells.Item(8, 1).Value2 === "1E12" &&
            sh.Cells.Item(2, 3).Value2 === "000123" && stats.failed === 0 && stats.batches > 0;
        message = skuReport(stats);
    } catch (err) { skuAddinError(err); message = String(err.message || err); }
    finally { app.EnableEvents = oldEvents; SKU_RUN.enabled = oldAuto; }
    alert((passed ? "WPS批量接口自测通过。" : "WPS批量接口自测未通过，请查看兼容处理数量及错误。") + "\n已新建未保存的测试工作簿，现有文件未用于自测。\n\n" + message);
}
function SkuAddinHelp() {
    alert("SKU工具 v1.0.5\n\n打开文件和切换工作表不再扫描。每次启动自动处理默认暂停。\n先点击处理当前表；可开启当前文件的输入/粘贴自动处理，不扫描其他文件。\n普通数据按1000行一块批量读写，异常区域隔离处理。可用2万行测速查看实际用时；可查看状态/停止处理；停止保留已完成修改，不自动保存。\n表头仅检查前20行、前256列。含SKU文字、大小写不限。\n每个任务最多20万个SKU单元格，超出请用处理所选区域分次处理。\n纯数字整数转数值，自定义格式0；前导零会去掉。\n非纯数字也清理空格/隐藏字符/前置单引号，按文本存储并设为0格式。\n超过15位有效数字、公式保留；跳过合并单元格、错误及受保护表。\n空单元格不写格式。表头单独变化不扫描整表；已有数据用按钮处理。\n安装后先保存文件，完全退出WPS再重新打开，才能卸载内存中的旧版。");
}

function SkuAddinBenchmark() {
    if (SKU_RUN.current || SKU_RUN.pending.length) { alert("请先等待当前任务完成或点击停止处理，再测速。"); return; }
    var app = Application, oldEvents, oldScreen, captured = false, book, sh;
    try {
        oldEvents = app.EnableEvents; oldScreen = app.ScreenUpdating; captured = true;
        app.EnableEvents = false; app.ScreenUpdating = false;
        book = app.Workbooks.Add(); sh = book.Worksheets.Item(1); sh.Name = "SKU两万行测速";
        sh.Range("A1:B1").Value2 = [["公司sku", "平台sku"]];
        var values = [];
        for (var r = 0; r < 20000; r++) values.push(["000123", " 'AB C-１２３ "]);
        sh.Range("A2:B20001").NumberFormat = "@";
        sh.Range("A2:B20001").Value2 = values;
    } catch (err) { alert("无法创建测速表: " + String(err.message || err)); return; }
    finally { if (captured) { try { app.ScreenUpdating = oldScreen; } finally { app.EnableEvents = oldEvents; } } }
    try {
        skuQueue(book, [sh], null, true);
        SKU_RUN.pending[SKU_RUN.pending.length - 1].benchmark = true;
    } catch (err) { alert("无法开始测速: " + String(err.message || err)); }
}
